CLUSTER_NAME := testsg.useast1.dev.stem.com
SSH_PUBLIC_KEY := ~/.ssh/testsg.useast1.dev.stem.com.pub
DNS_ZONE := dev.stem.com
KOPS_STATE_STORE := s3://useast1.dev.stem.com
REGION := us-east-1
NETWORK_CIDR := 10.16.0.0/16
LB_TYPE := Internal
include ../Makefile.in
